# Generated by Django 2.1 on 2018-08-13 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nicknames', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='dorm',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.College'),
        ),
    ]
