# Generated by Django 2.1 on 2018-08-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_auto_20180813_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='nicknames',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
