# Generated by Django 2.1 on 2018-08-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_auto_20180814_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='url',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
