# Generated by Django 2.1 on 2018-08-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_college_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='url',
            field=models.CharField(max_length=20),
        ),
    ]
